version: '3.3'
services:

  todo-service:
    build:
      context: ./
      dockerfile: ./docker/TodoService/dockerfile

  todo-webapp:
    build:
      context: ./
      dockerfile: ./docker/TodoWebApp/dockerfile