apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: todo-webapp-deployment
spec:
  selector:
      matchLabels:
          app: todo-app
          component: todo-webapp
  replicas: 1
  template:
    metadata:
      labels:
        component: todo-webapp
        app: todo-app
        version: v1
    spec:      
      imagePullSecrets:
        - name: regcred
      containers:
      - name: todo-webapp
        image: tstraubk8shackfest.azurecr.io/todo-webapp:v1
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: K8s
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-webapp-service
spec:
  selector:
    component: todo-webapp
    version: v1
  ports:
  - port: 51101
    targetPort: 80
    name: http
  type: LoadBalancer